trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  organisation: 'maxxiltest'
  projet: 'Poc_Pipeline'
  wikiID: 'Wiki1'
  connectionToken: '$(myToken)'  

steps:
- powershell: |
    Write-Host "Récupération du dernier commit"
    $commitHash = git log -1 --pretty=format:"%H"
    $commitMsg = git log -1 --pretty=format:"%s"

    Write-Host "Commit : $commitMsg"
    Write-Host "Hash   : $commitHash"

    $pageName = "$commitMsg - $commitHash"
    $content = "## Page créée automatiquement`nCommit: $commitMsg`nHash: $commitHash"

    Write-Host "Création de la page: $pageName"

    # Authentification
    $connectionToken = "$env:connectionToken"
    $base64AuthInfo = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes(":$connectionToken"))

    # Construction de l'URL
    #$encodedPageName = [System.Web.HttpUtility]::UrlEncode($pageName)
    $wikiUri = "https://dev.azure.com/$env:organisation/$env:projet/_apis/wiki/wikis/$env:wikiID/pages?path=/$pageName&api-version=7.1-preview.1"

    # Appel PUT pour créer ou mettre à jour une page
    Invoke-RestMethod -Uri $wikiUri `
        -Headers @{ Authorization = "Basic $base64AuthInfo" } `
        -Method Put `
        -ContentType "application/json" `
        -Body (@{
            content = $content
        } | ConvertTo-Json -Depth 3)
  displayName: 'Créer une page Wiki avec le dernier commit'
