trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Récupération du dernier commit"
    COMMIT_HASH=$(git log -1 --pretty=format:"%H")
    COMMIT_MSG=$(git log -1 --pretty=format:"%s")

    echo "Commit : $COMMIT_MSG"
    echo "Hash   : $COMMIT_HASH"

    # Nom de la page
    PAGE_NAME="${COMMIT_MSG} - ${COMMIT_HASH}"
    PAGE_NAME_ESCAPED=$(echo "$PAGE_NAME" | jq -s -R -r @uri)

    # Contenu de la page en Markdown
    CONTENT="# Détails du commit\n- **Message** : $COMMIT_MSG\n- **Hash** : $COMMIT_HASH"

    echo "Création de la page wiki $PAGE_NAME"

    curl -X PUT \
      -H "Content-Type: application/json" \
      -H "Authorization: Basic $(echo -n :$SYSTEM_ACCESSTOKEN | base64)" \
      "https://dev.azure.com/$(organisation)/$(projet)/_apis/wiki/wikis/$(wikiID)/pages?path=/$PAGE_NAME_ESCAPED&api-version=7.1-preview.1" \
      -d "$(jq -n --arg content "$CONTENT" '{content: $content}')"
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  displayName: "Créer une page Wiki"
