trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  organisation: 'maxxiltest'
  projet: 'Poc_Pipeline'
  wikiID: 'Wiki1'

steps:
- script: |
    echo "Récupération du dernier commit"
    COMMIT_HASH=$(git log -1 --pretty=format:"%H")
    COMMIT_MSG=$(git log -1 --pretty=format:"%s")

    echo "Commit : $COMMIT_MSG"
    echo "Hash   : $COMMIT_HASH"

    # On limite le message à 50 caractères max pour éviter les erreurs d'URL
    COMMIT_MSG_TRIMMED=$(echo "$COMMIT_MSG" | cut -c1-50)

    # Construction du nom de la page
    PAGE_NAME="${COMMIT_MSG_TRIMMED} - ${COMMIT_HASH}"
    PAGE_NAME_ESCAPED=$(echo "$PAGE_NAME" | jq -s -R -r @uri)

    # Contenu Markdown
    CONTENT="# Détails du commit\n- **Message** : $COMMIT_MSG\n- **Hash** : $COMMIT_HASH"

    echo "Création de la page wiki $PAGE_NAME"

    curl -X PUT \
      -H "Content-Type: application/json" \
      -H "Authorization: Basic $(echo -n :$SYSTEM_ACCESSTOKEN | base64)" \
      "https://dev.azure.com/$(organisation)/$(projet)/_apis/wiki/wikis/$(wikiID)/pages?path=/$PAGE_NAME_ESCAPED&api-version=7.1-preview.1" \
      -d "$(jq -n --arg content "$CONTENT" '{content: $content}')"
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  displayName: "Créer une page Wiki"
