trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    Write-Host "Récupération du dernier commit"
    $commitHash = git log -1 --pretty=format:"%H"
    $commitMsg = git log -1 --pretty=format:"%s"
    Write-Host "Commit : $commitMsg"
    Write-Host "Hash   : $commitHash"

    $pageName = "$commitMsg - $commitHash"
    $content = "Contenu de la page"

    Write-Host "Création de la page: $pageName"

    $encodedPageName = [System.Uri]::EscapeDataString("/RELEASE NOTE - DEVELOP/$pageName")

    $token = "$(myToken)"
    $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$token"))

    $uri =  "https://dev.azure.com/$(organisation)/$(projet)/_apis/wiki/wikis/$(WikiID)/pages?path=$encodedPageName&api-version=7.1-preview.1"
    Invoke-RestMethod -Uri $uri `
        -Headers @{Authorization = "Basic $base64AuthInfo"} `
        -Method PUT `
        -ContentType "application/json" `
        -Body (@{ content = $content } | ConvertTo-Json -Depth 10)
  displayName: 'Créer une page Wiki avec le dernier commit'
  
- task: EmailReportV2@2
  inputs:
    sendMailConditionConfig: 'Always'
    subject: '[{environmentStatus}] {passPercentage} tests passed in $(Release.EnvironmentName) stage for $(Build.BuildNumber)'
    toAddress: 'yoann.vernay@cgi.com'
    defaultDomain: 'microsoft.com'
    groupTestResultsBy: 'run'
    includeCommits: true
    maxTestFailuresToShow: '15'
    includeOthersInTotal: false
    usePreviousEnvironment: false