trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  organisation: 'maxxiltest'
  projet: 'Poc_Pipeline'
  wikiID: 'Wiki1'

steps:
- script: |
    echo "Récupération du dernier commit"
    COMMIT_HASH=$(git log -1 --pretty=format:"%H")
    COMMIT_MSG=$(git log -1 --pretty=format:"%s")

    echo "Commit : $COMMIT_MSG"
    echo "Hash   : $COMMIT_HASH"

    PAGE_NAME="${COMMIT_MSG} - ${COMMIT_HASH}"
    CONTENT="Contenu de la page"

    echo "Création de la page: $PAGE_NAME"
