
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  organisation: 'maxxiltest'
  projet: 'Poc_Pipeline'
  wikiID: 'Wiki1'

steps:
- powershell: |
    Write-Host "Récupération du dernier commit"
    $commitHash = git log -1 --pretty=format:"%H"
    $commitMsg = git log -1 --pretty=format:"%s"

    Write-Host "Commit : $commitMsg"
    Write-Host "Hash   : $commitHash"

    $pageName = "$commitMsg - $commitHash"
    $content = "Contenu de la page"

    Write-Host "Création de la page: $pageName"